---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-demo
  name: jenkins-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: neroxxpips/jenkins-demo:latest
        name: jenkins-demo
        ports:
            - containerPort: 3000
        resources: {}
status: {}
