apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-demo
  name: jenkins-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: jenkins-demo