apiVersion: v1
kind: Service
metadata:
  labels:
    app: actions-demo
  name: actions-demo-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: actions-demo